"""Regenerates screentime_domains.json from scratch: the hand-curated seed
in screentime_domains_curated.json (always wins on conflict) merged with a
fresh pull of the UT1 blacklists (github.com/olbat/ut1-blacklists, CC
BY-SA), which supply Games/Education/Entertainment domains at a scale no
one would hand-curate. There is no equivalent free bulk dataset for
Entertainment/Education/Games/Tools by *executable name* -- Tools has no
UT1 source either (it's a content-filtering blacklist, not a general
software catalog) -- so screentime_categories.py's small _APP_CATEGORIES
map stays hand-maintained; this script only ever touches domains.

Run from the carmen-desktop repo root:
    python scripts/update_screentime_domains.py

Deliberately regenerates the whole output file every run rather than
patching the previous one in place -- re-merging into an already-merged
file would let removed/renamed UT1 entries linger forever and makes the
"curated always wins" rule harder to reason about than just recomputing
curated + fresh-UT1 from the two real sources of truth each time.

Prints a summary (added/removed/changed counts per category) to stdout for
a caller (e.g. a scheduled job opening a PR) to fold into a description.
"""
import json
import os
import re
import sys
import urllib.request
from collections import Counter

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CURATED_PATH = os.path.join(REPO_ROOT, "screentime_domains_curated.json")
OUTPUT_PATH = os.path.join(REPO_ROOT, "screentime_domains.json")

UT1_BASE = "https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/"
# category -> list of UT1 blacklist names to merge into it. UT1 has nothing
# usable for "Tools" (see module docstring), so there's no entry for it here.
UT1_SOURCES = {
    "Games": ["games"],
    "Education": ["educational_games", "liste_bu"],
    "Entertainment": ["social_networks", "audio-video", "chat", "manga", "radio", "sports"],
}

_DOMAIN_RE = re.compile(r"^[a-z0-9.\-]+$")
_IPV4_RE = re.compile(r"^\d+\.\d+\.\d+\.\d+$")

_COMMENT = (
    "Domain-to-category map (Entertainment / Education / Games / Tools). "
    "Sourced from two places: (1) screentime_domains_curated.json, a small "
    "hand-curated set of well-known sites (the ones without an obvious "
    "blocklist-style source -- search engines, dev tools, productivity "
    "software, streaming services), always authoritative; and (2) the "
    "Universite Toulouse Capitole UT1 blacklists "
    "(github.com/olbat/ut1-blacklists, CC BY-SA) for Games (their games/ "
    "list), Education (liste_bu/ -- university library/academic resources "
    "-- and educational_games/), and Entertainment (social_networks/, "
    "audio-video/, chat/, manga/, radio/, sports/). UT1 has no "
    "general-purpose \"productivity tools\" category, so Tools stays "
    "hand-curated and is the thinnest of the four. Anything not in this "
    "file falls back to \"Other\" in screentime_categories.py. "
    "Regenerated by scripts/update_screentime_domains.py -- do not hand-edit; "
    "edit screentime_domains_curated.json instead."
)


def fetch_ut1_domains(name):
    url = UT1_BASE + name + "/domains"
    with urllib.request.urlopen(url, timeout=30) as resp:
        text = resp.read().decode("utf-8", errors="ignore")

    domains = []
    for line in text.splitlines():
        d = line.strip().lower()
        if not d or d.startswith("#"):
            continue
        if _IPV4_RE.match(d) or "." not in d or not _DOMAIN_RE.match(d):
            continue
        domains.append(d)
    return domains


def build():
    with open(CURATED_PATH, "r", encoding="utf-8") as f:
        curated = json.load(f)
    curated.pop("_comment", None)

    merged = dict(curated)
    added_by_category = Counter()
    skipped_by_category = Counter()

    for category, sources in UT1_SOURCES.items():
        for source in sources:
            for domain in fetch_ut1_domains(source):
                if domain in merged:
                    skipped_by_category[category] += 1
                    continue
                merged[domain] = category
                added_by_category[category] += 1

    for domain in curated:
        merged[domain] = curated[domain]

    return merged, added_by_category, skipped_by_category


def main():
    old = {}
    if os.path.exists(OUTPUT_PATH):
        with open(OUTPUT_PATH, "r", encoding="utf-8") as f:
            old = json.load(f)
        old.pop("_comment", None)

    merged, added_by_category, skipped_by_category = build()

    output = {"_comment": _COMMENT}
    output.update(sorted(merged.items()))
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2)
        f.write("\n")

    old_keys, new_keys = set(old), set(merged)
    truly_added = new_keys - old_keys
    removed = old_keys - new_keys
    changed_category = {
        d for d in (old_keys & new_keys) if old[d] != merged[d]
    }

    print(f"Total domains: {len(old)} -> {len(merged)}")
    print(f"Newly added: {len(truly_added)}")
    print(f"Removed (dropped from upstream UT1 lists): {len(removed)}")
    print(f"Recategorized: {len(changed_category)}")
    print("Added by category (this run's UT1 fetch, before dedup against old file):")
    for category, count in added_by_category.items():
        print(f"  {category}: +{count} new, {skipped_by_category[category]} already known")

    if not truly_added and not removed and not changed_category:
        print("NO_CHANGES")
        return 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
